出来ました！！！！！
misonikomipan/ICA_practice pull request #1
Opened 2022-04-16 10:00 UTC by pipikouki

hub.m : ICAの入力
func_ICA.m : 分離を行う関数。擬距離のグラフ表示もする
func_laplace : スコア関数
func_dif_laplace : log(スコア関数)を微分したもの
func_picture : グラフの編集をする
under_construction.m : 関数に分ける前のファイル。関係ない。
combined_speech : 声を混ぜたもの（入力）
make_voice : 声を分離したもの（出力）

make_voice11 make_voice21 の二つが分離しきってない気がするのですが、気にしないことにしました。

よろしくお願いします。

2022-04-17 15:09 UTC, pipikouki commented
夜中に通知来たらごめんなさい。でもいいものできました！内容を以下に示します。

多入力の音源分離をするとき、たくさんのファイル名の入力がめんどくさかったです。なので、指定したフォルダにあるデータ全てにICAするというものにしました。

call_main.m : mainの入力がめんどくさいので書いた。これ実行したら全部い感じに動く。
func_main.m : 指定されたファイルの中のデータを全部読み込む、結合して行列にする、ICA関数に渡す。結果をファイル出力する。
func_ICA.m : 同封pdfの最後の方にあるやつとほとんど同じ。多入力にしただけ。ICAする。
func_picture.m : グラフ表示。いらん。
score_func_~~ : スコア関数とその微分。

よろしくお願いします！！！

2022-04-18 06:14 UTC, pipikouki commented
お昼休みは貴重なお時間をいただき、ありがとうございました。昼休み後の格闘の末、解決することができました。
原因は代入する値が間違っていました。結果は、完全に分離された音、それっぽいグラフだったので間違いないと思われます。
ここから余談です。綾野君と速さ勝負をしたところ、圧倒的に僕が遅かったです。この原因は、ベクトルの成分ごとにスコア関数を計算していることだと思われます（綾野君はベクトル単位で計算）。気がむいたら直します。

2022-04-19 08:03 UTC, misonikomipan requested changes
アルゴリズムは資料通りに実装できていると思います！
細々とした点（相対パス、関数の説明コメント等）で指摘しているのでそこだけ修正してください！

2022-04-20 00:13 UTC, misonikomipan approved these changes
マージしておきます

2022-04-20 00:13 UTC, misonikomipan commented on call_main.m
>  score_func_dif = @score_func_laplace_dif;   %優ガウス分布をlogとって微分
いいね👍

2022-04-20 00:13 UTC, misonikomipan commented on func_main.asv
> +end
asvファイル、いらないのでリポジトリから削除しときます

2022-04-20 00:13 UTC, misonikomipan commented on func_main.m
> +    audiowrite("./" + folder_name + "_result/result" + i + ".wav",get_data(:,i),Fs);
おしゃれ

2022-04-20 00:13 UTC, misonikomipan commented on func_main.m
> +addpath("function")
おしゃれ

2022-04-20 00:13 UTC, misonikomipan commented on function/func_ICA.m
> +output_mat = output_mat';
プロジェクションバックやってないの普通に見落としてた！
OKです

2022-04-20 00:13 UTC, merged

2022-04-20 09:39 UTC, pipikouki commented
SDR値確認しました！！！！
   13.2419
   13.7822
らしいです。good！！！！